-- MySQL Script generated by MySQL Workbench
-- Sun Jun  8 19:16:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_DignCare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_DignCare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_DignCare` DEFAULT CHARACTER SET utf8 ;
USE `db_DignCare` ;

-- -----------------------------------------------------
-- Table `db_DignCare`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_DignCare`.`localizacao` (
  `local_id` INT NOT NULL,
  `local_cep` INT NOT NULL,
  `local_numero` INT NOT NULL,
  `local_referencia` VARCHAR(50) NULL,
  PRIMARY KEY (`local_id`),
  UNIQUE INDEX `local_id_UNIQUE` (`local_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_DignCare`.`tipoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_DignCare`.`tipoServico` (
  `tipoServico_id` INT NOT NULL,
  `tipoServico_nome` VARCHAR(45) NOT NULL,
  `tipoServico_desc` VARCHAR(500) NULL,
  PRIMARY KEY (`tipoServico_id`),
  UNIQUE INDEX `tipoServico_id_UNIQUE` (`tipoServico_id` ASC) VISIBLE,
  UNIQUE INDEX `tipoServico_nome_UNIQUE` (`tipoServico_nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_DignCare`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_DignCare`.`avaliacao` (
  `avaliacao_id` INT NOT NULL,
  `avaliacao_nota` INT NOT NULL,
  `avaliacao_data` DATE NOT NULL,
  `avaliacao_descricao` VARCHAR(500) NULL,
  PRIMARY KEY (`avaliacao_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_DignCare`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_DignCare`.`usuario` (
  `usr_id` INT NOT NULL AUTO_INCREMENT,
  `usr_nome` VARCHAR(50) NOT NULL,
  `usr_cpf` VARCHAR(45) NOT NULL,
  `usr_idade` INT NOT NULL,
  `usr_tipo` VARCHAR(45) NOT NULL,
  `usr_email` VARCHAR(45) NOT NULL,
  `usr_senha` VARCHAR(16) NOT NULL,
  `local_id` INT NULL,
  `tipoServico_id` INT NULL,
  `avaliacao_id` INT NULL,
  PRIMARY KEY (`usr_id`),
  UNIQUE INDEX `usr_cpf_UNIQUE` (`usr_cpf` ASC) VISIBLE,
  UNIQUE INDEX `usr_email_UNIQUE` (`usr_email` ASC) VISIBLE,
  INDEX `tipoServico_id_idx` (`tipoServico_id` ASC) VISIBLE,
  INDEX `local_id_idx` (`local_id` ASC) VISIBLE,
  INDEX `avaliacao_id_idx` (`avaliacao_id` ASC) VISIBLE,
  CONSTRAINT `local_id`
    FOREIGN KEY (`local_id`)
    REFERENCES `db_DignCare`.`localizacao` (`local_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoServico_id`
    FOREIGN KEY (`tipoServico_id`)
    REFERENCES `db_DignCare`.`tipoServico` (`tipoServico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avaliacao_id`
    FOREIGN KEY (`avaliacao_id`)
    REFERENCES `db_DignCare`.`avaliacao` (`avaliacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_DignCare`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_DignCare`.`servico` (
  `servico_id` INT NOT NULL,
  `user_id_contratante` INT NOT NULL,
  `user_id_contratado` INT NOT NULL,
  `local_id` INT NOT NULL,
  `tipoServico_id` INT NOT NULL,
  `servico_data_criado` DATE NOT NULL,
  `servico_data_realizado` DATE NOT NULL,
  `avaliacao_id` INT NULL,
  PRIMARY KEY (`servico_id`),
  
  -- Índices
  INDEX `user_id_contratante_idx` (`user_id_contratante` ASC) VISIBLE,
  INDEX `user_id_contratado_idx` (`user_id_contratado` ASC) VISIBLE,
  INDEX `local_id_idx` (`local_id` ASC) VISIBLE,
  INDEX `tipoServico_id_idx` (`tipoServico_id` ASC) VISIBLE,
  INDEX `avaliacao_id_idx` (`avaliacao_id` ASC) VISIBLE,

  -- Chaves estrangeiras
  CONSTRAINT `fk_user_id_contratante`
    FOREIGN KEY (`user_id_contratante`)
    REFERENCES `db_DignCare`.`usuario` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_user_id_contratado`
    FOREIGN KEY (`user_id_contratado`)
    REFERENCES `db_DignCare`.`usuario` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_local_id`
    FOREIGN KEY (`local_id`)
    REFERENCES `db_DignCare`.`localizacao` (`local_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_tipoServico_id`
    FOREIGN KEY (`tipoServico_id`)
    REFERENCES `db_DignCare`.`tipoServico` (`tipoServico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_avaliacao_id`
    FOREIGN KEY (`avaliacao_id`)
    REFERENCES `db_DignCare`.`avaliacao` (`avaliacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
